all:
  hosts:
    Router1:
      ansible_host: 192.168.220.1
      ansible_port: 10022
      ansible_user: vagrant
      ansible_password: vagrant
    Router2:
      ansible_host: 192.168.220.1
      ansible_port: 11022
      ansible_user: vagrant
      ansible_password: vagrant
    Router3: 
      ansible_host: 192.168.220.1
      ansible_port: 12022
      ansible_user: vagrant
      ansible_password: vagrant
